export const data = [
  {
    creative_id: "120214081337200422",
    creative_name: "New Creative 4",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - New Creatives",
    ad_group: "New Creatives",
    ipm: 2.700113231,
    ctr: 0.844874,
    spend: 7.01,
    impressions: 11481,
    clicks: 97,
    cpm: 0.610574,
    cpc: 0.072268,
    cpi: 0.2261290323,
    installs: 31,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "download it and start crushing those levels!",
      objects: ["colored bubbles", "wand", "rocks", "boots"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Middle-Right",
      bgcolor: "Orange",
      bgsetting: "fantasy",
      ctabgcolor: "Dark Purple",
    },
  },
  {
    creative_id: "120214081106690422",
    creative_name: "New Creative 5",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - New Creatives",
    ad_group: "New Creatives",
    ipm: 1.883561644,
    ctr: 0.770548,
    spend: 2.95,
    impressions: 5840,
    clicks: 45,
    cpm: 0.505137,
    cpc: 0.065556,
    cpi: 0.2681818182,
    installs: 11,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download today and start merging!",
      objects: ["large brown mushrooms", "trees", "a wand"],
      ctalanguage: "English",
      logopresent: "yes",
      cta_placement: "Bottom-Center",
      bgcolor: "Orange",
      bgsetting: "forest",
      ctabgcolor: "Dark Purple",
    },
  },
  {
    creative_id: "120214096349490422",
    creative_name: "Creative 2",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives – Revised",
    ipm: 1.603750308,
    ctr: 0.826548,
    spend: 5.05,
    impressions: 8106,
    clicks: 67,
    cpm: 0.622995,
    cpc: 0.075373,
    cpi: 0.3884615385,
    installs: 13,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download and play for free!",
      objects: ["purple and red mushrooms", "crystals", "magnet", "bomb"],
      ctalanguage: "English",
      logopresent: "yes",
      cta_placement: "Middle-Center",
      bgcolor: "light blue",
      bgsetting: "bedroom",
      ctabgcolor: "light-blue",
    },
  },
  {
    creative_id: "120214081106700422",
    creative_name: "New Creative 1",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - New Creatives",
    ad_group: "New Creatives",
    ipm: 0.6657789614,
    ctr: 0.732357,
    spend: 0.75,
    impressions: 1502,
    clicks: 11,
    cpm: 0.499334,
    cpc: 0.068182,
    cpi: 0.75,
    installs: 1,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download now!",
      objects: ["colored bubbles", "wand", "game screen"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "Yellowish Orange",
      bgsetting: "forest",
      ctabgcolor: "Purple",
    },
  },
  {
    creative_id: "120214096349510422",
    creative_name: "Creative 3",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives – Revised",
    ipm: 0.6373486297,
    ctr: 0.478011,
    spend: 2.85,
    impressions: 6276,
    clicks: 30,
    cpm: 0.454111,
    cpc: 0.095,
    cpi: 0.7125,
    installs: 4,
    tags: {
      concept: "UGC",
      atype: "Voiceover",
      alanguage: "English",
      cta: "Download Bubblewise now",
      objects: ["blue crystals", "pink petals", "red mushrooms"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "light blue",
      bgsetting: "game",
      ctabgcolor: "White",
    },
  },
  {
    creative_id: "120214096349530422",
    creative_name: "Creative 4",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives – Revised",
    ipm: 0.4719207173,
    ctr: 0.589901,
    spend: 1.77,
    impressions: 4238,
    clicks: 25,
    cpm: 0.41765,
    cpc: 0.0708,
    cpi: 0.885,
    installs: 2,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download Bubblewise today",
      objects: ["bat shaped bubble", "mushroom shaped bubble", "potion bottle"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "pale green",
      bgsetting: "game screen",
      ctabgcolor: "White",
    },
  },
  {
    creative_id: "120216118074910422",
    creative_name: "New App promotion ad",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "Test for Daga: boosting",
    ad_group: "Partnership",
    ipm: 0.4719207173,
    ctr: 0.589901,
    spend: 1.77,
    impressions: 4238,
    clicks: 25,
    cpm: 0.41765,
    cpc: 0.0708,
    cpi: 0.885,
    installs: 2,
    tags: {
      concept: "",
      atype: "",
      alanguage: "",
      cta: "",
      objects: [],
      ctalanguage: "",
      logopresent: "",
      cta_placement: "",
      bgcolor: "",
      bgsetting: "",
      ctabgcolor: "",
    },
  },
  {
    creative_id: "120214081106680422",
    creative_name: "New Creative 3",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - New Creatives",
    ad_group: "New Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Play now and prove your strategy skills!",
      objects: ["wooden crib", "door handle"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Middle-Right",
      bgcolor: "White",
      bgsetting: "forest",
      ctabgcolor: "White",
    },
  },
  {
    creative_id: "120214080965820422",
    creative_name: "Creative 2",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download and play for free!",
      objects: ["purple and red mushrooms", "crystals", "magnet", "bomb"],
      ctalanguage: "English",
      logopresent: "yes",
      cta_placement: "Middle-Center",
      bgcolor: "light blue",
      bgsetting: "bedroom",
      ctabgcolor: "light-blue",
    },
  },
  {
    creative_id: "120214078111440422",
    creative_name: "Creative 1",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "Voiceover",
      alanguage: "English",
      cta: "TRY AGAIN",
      objects: [
        "skull bubble",
        "bone bubble",
        "mushroom bubble",
        "gem bubble",
        "bomb bubble",
        "cage with bat wings",
      ],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "Periwinkle",
      bgsetting: "purple",
      ctabgcolor: "Orange",
    },
  },
  {
    creative_id: "120214080965830422",
    creative_name: "Creative 3",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "Voiceover",
      alanguage: "English",
      cta: "Download Bubblewise now",
      objects: ["blue crystals", "pink petals", "red mushrooms"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "light blue",
      bgsetting: "game",
      ctabgcolor: "White",
    },
  },
  {
    creative_id: "120214080965840422",
    creative_name: "Creative 4",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "voiceover",
      alanguage: "English",
      cta: "Download Bubblewise today",
      objects: ["bat shaped bubble", "mushroom shaped bubble", "potion bottle"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "pale green",
      bgsetting: "game screen",
      ctabgcolor: "White",
    },
  },
  {
    creative_id: "120214096349500422",
    creative_name: "Creative 1",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - OG Creatives",
    ad_group: "OG Creatives – Revised",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "Voiceover",
      alanguage: "English",
      cta: "TRY AGAIN",
      objects: [
        "skull bubble",
        "bone bubble",
        "mushroom bubble",
        "gem bubble",
        "bomb bubble",
        "cage with bat wings",
      ],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Bottom-Center",
      bgcolor: "Periwinkle",
      bgsetting: "purple",
      ctabgcolor: "Orange",
    },
  },
  {
    creative_id: "120214081106650422",
    creative_name: "New Creative 2",
    country: "IN",
    ad_network: "meta",
    os: "unknown",
    campaign: "App promotion campaign - New Creatives",
    ad_group: "New Creatives",
    ipm: 0,
    ctr: 0,
    spend: 0,
    impressions: 0,
    clicks: 0,
    cpm: 0,
    cpc: 0,
    cpi: 0,
    installs: 0,
    tags: {
      concept: "UGC",
      atype: "Voiceover",
      alanguage: "English",
      cta: "Play now and prove your",
      objects: ["bubble with a face, multiple", "wand", "trees", "ground"],
      ctalanguage: "English",
      logopresent: "",
      cta_placement: "Middle-Center",
      bgcolor: "Golden Yellow",
      bgsetting: "forest",
      ctabgcolor: "purple",
    },
  }
];
